# Generated by Django 4.2.5 on 2023-09-29 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingridient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('allergen', models.BooleanField(default=False, verbose_name='Аллерген')),
                ('price', models.FloatField(verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Ингридиент',
                'verbose_name_plural': 'Ингридиенты',
            },
        ),
        migrations.AlterField(
            model_name='bot_user',
            name='name',
            field=models.CharField(max_length=200, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Изображение'),
        ),
        migrations.CreateModel(
            name='ReceptItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.dish')),
                ('ingridient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.ingridient')),
            ],
        ),
        migrations.AddField(
            model_name='dish',
            name='ingridients',
            field=models.ManyToManyField(blank=True, related_name='Dishes', through='bot.ReceptItem', to='bot.ingridient'),
        ),
    ]
