# Generated by Django 4.2.5 on 2023-09-29 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_ingridient_alter_bot_user_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receptitem',
            options={'verbose_name': 'Ингридиент', 'verbose_name_plural': 'Ингридиенты'},
        ),
        migrations.AddField(
            model_name='bot_user',
            name='favorites',
            field=models.ManyToManyField(related_name='DishesLikes', to='bot.dish'),
        ),
        migrations.AddField(
            model_name='receptitem',
            name='unit',
            field=models.CharField(choices=[('грамм', 'Gram'), ('штука', 'Piece')], default='PIECE', max_length=255, verbose_name='Единица измерения'),
        ),
        migrations.AlterField(
            model_name='receptitem',
            name='ingridient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.ingridient', verbose_name='Ингридиент'),
        ),
        migrations.AlterField(
            model_name='receptitem',
            name='quantity',
            field=models.IntegerField(verbose_name='Количество'),
        ),
    ]
