# Generated by Django 4.2.5 on 2023-09-29 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_alter_receptitem_options_bot_user_favorites_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receptitem',
            name='unit',
            field=models.CharField(choices=[('грамм', 'Gram'), ('штука', 'Piece'), ('Киллограмм', 'Kg')], default='PIECE', max_length=255, verbose_name='Единица измерения'),
        ),
        migrations.CreateModel(
            name='Pay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_date', models.DateTimeField(auto_now=True, verbose_name='Дата оплаты')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Users_pays', to='bot.bot_user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
            },
        ),
    ]
