# Generated by Django 4.2.5 on 2023-09-30 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_pay_summ'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pay',
            name='pay_date',
            field=models.DateTimeField(verbose_name='Дата оплаты'),
        ),
    ]
