# Generated by Django 4.2.5 on 2023-10-02 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_alter_pay_pay_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingridient',
            name='count',
            field=models.IntegerField(default=0, verbose_name='Количество'),
        ),
    ]
